name: test
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    name: tests
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      - name: run unit test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic
      - name: run benchmark
        run: go test -benchmem -bench .
      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
