name: test
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    name: tests with go1.14
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1
      - name: Setup go
        uses: actions/setup-go@v2-beta
        with:
          go-version: "^1.14"
      - name: run unit test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
