name: test
on:
  - push
  - pull_request
jobs:
  test_1_13:
    runs-on: ubuntu-latest
    name: tests with go1.13
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2-beta
        with:
          go-version: "^1.13"
      - name: run unit test
        run: go test -v
      - name: run benchmark
        run: go test -benchmem -bench .

  test_1_14:
    runs-on: ubuntu-latest
    name: tests with go1.14
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2-beta
        with:
          go-version: "^1.14"
      - name: run unit test
        run: go test -v
      - name: run benchmark
        run: go test -benchmem -bench .

  test_1_15:
    runs-on: ubuntu-latest
    name: tests with go1.15
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1
      - name: Setup go
        uses: actions/setup-go@v2-beta
        with:
          go-version: "^1.15"
      - name: run unit test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic
      - name: run benchmark
        run: go test -benchmem -bench .
      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
